spring.application.name=api-gateway
server.port=${SERVER_PORT:8080}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never
management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState
logging.level.root=${LOG_LEVEL:INFO}
spring.cloud.gateway.server.webflux.routes[0].id=auth
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_BASE_URL:http://auth-service:8080}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[1].id=customer
spring.cloud.gateway.server.webflux.routes[1].uri=${CUSTOMER_BASE_URL:http://customer-service:8080}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/customers/**
spring.cloud.gateway.server.webflux.routes[2].id=order
spring.cloud.gateway.server.webflux.routes[2].uri=${ORDER_BASE_URL:http://order-service:8080}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=2000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=8s
